services:
  timescale: # this name is resolved and can be used by the other servers instead of an ip
    image: timescale/timescaledb:latest-pg18
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/pgdata
      - ./timescale/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file: general.env
  
  etl:
    build: ./etl/
    env_file: general.env
    environment:
      - PYTHONUNBUFFERED=1 # needed so that pythons print output is visible in the logs
